/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import controlador.analizarCadenasControlador;
import java.io.File;

/**
 *
 * @author jciri
 */
public class grafica extends javax.swing.JFrame {

    /**
     * Creates new form grafica
     */
    public grafica() {
        initComponents();
    }
    //get and setters de la cadena evaluada 

    public JTextField getCadenaEvaluada() {
        return cadenaEvaluada;
    }

    public void setCadenaEvaluada(JTextField cadenaEvaluada) {
        this.cadenaEvaluada = cadenaEvaluada;
    }

    //tabla
    public JTable getTablaSentencias() {
        return tablaSentencias;
    }

    public void setTablaSentencias(JTable tablaSentencias) {
        this.tablaSentencias = tablaSentencias;
    }

    //mostrarImagen
    public JLabel getLabelImagen() {
        return LabelImagen;
    }

    public void setLabelImagen(JLabel LabelImagen) {
        this.LabelImagen = LabelImagen;
    }

    //aca hicimos otro cambio
    private analizarCadenasControlador controlador;

    public void setControlador(analizarCadenasControlador controlador) {
        this.controlador = controlador;
    }

    //elemento evaluado 
    public JTextField getElementoEvaluado() {
        return elementoEvaluado;
    }

    public void setElementoEvaluado(JTextField elementoEvaluado) {
        this.elementoEvaluado = elementoEvaluado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelImagen = new javax.swing.JLabel();
        btnAdelanteSimbolo = new javax.swing.JButton();
        btnAtrasSimbolo = new javax.swing.JButton();
        cadenaEvaluada = new javax.swing.JTextField();
        btnSiguienteCadena = new javax.swing.JButton();
        btnAtrasCadena = new javax.swing.JButton();
        regresarPagina = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaSentencias = new javax.swing.JTable();
        elementoEvaluado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdelanteSimbolo.setText("Adelante");
        btnAdelanteSimbolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteSimboloActionPerformed(evt);
            }
        });

        btnAtrasSimbolo.setText("Atras");
        btnAtrasSimbolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasSimboloActionPerformed(evt);
            }
        });

        btnSiguienteCadena.setText("siguiente Cadena");
        btnSiguienteCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteCadenaActionPerformed(evt);
            }
        });

        btnAtrasCadena.setText("Cadena anteriror");
        btnAtrasCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCadenaActionPerformed(evt);
            }
        });

        regresarPagina.setText("Regresar Pagina");
        regresarPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarPaginaActionPerformed(evt);
            }
        });

        tablaSentencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaSentencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdelanteSimbolo)
                        .addGap(34, 34, 34)
                        .addComponent(btnAtrasSimbolo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadenaEvaluada, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementoEvaluado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAtrasCadena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguienteCadena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regresarPagina)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regresarPagina)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdelanteSimbolo)
                            .addComponent(btnAtrasSimbolo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadenaEvaluada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elementoEvaluado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguienteCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtrasCadena, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdelanteSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteSimboloActionPerformed
        if (controlador != null) {
            controlador.avanzarSimbolo();
        }
    }//GEN-LAST:event_btnAdelanteSimboloActionPerformed

    private void regresarPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarPaginaActionPerformed
        // 🔹 Primero eliminamos las imágenes antes de cerrar la ventana
        borrarImagenesGeneradas();

        // 🔹 Luego ocultamos la vista
        setVisible(false);
    }

    /**
     * 🔥 Elimina todos los archivos .png dentro de la carpeta
     * C:/AutomataFinito/tmp
     */
    private void borrarImagenesGeneradas() {
        String ruta = "C:/AutomataFinito/tmp";
        File carpeta = new File(ruta);

        if (!carpeta.exists() || !carpeta.isDirectory()) {
            System.out.println("⚠ La carpeta no existe o no es un directorio: " + ruta);
            return;
        }

        File[] archivos = carpeta.listFiles((dir, nombre) -> nombre.toLowerCase().endsWith(".png"));
        if (archivos == null || archivos.length == 0) {
            System.out.println("ℹ No hay imágenes para eliminar en: " + ruta);
            return;
        }

        int eliminados = 0;
        for (File archivo : archivos) {
            if (archivo.delete()) {
                eliminados++;
                System.out.println("🗑 Imagen eliminada: " + archivo.getName());
            } else {
                System.err.println("❌ No se pudo eliminar: " + archivo.getName());
            }
        }

        System.out.println("✅ Se eliminaron " + eliminados + " imágenes .png de la carpeta tmp.");
    }//GEN-LAST:event_regresarPaginaActionPerformed

    private void btnSiguienteCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteCadenaActionPerformed
        if (controlador != null) {
            controlador.siguienteCadena();
        }
    }//GEN-LAST:event_btnSiguienteCadenaActionPerformed

    private void btnAtrasCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCadenaActionPerformed
        if (controlador != null) {
            controlador.anteriorCadena();
        }
    }//GEN-LAST:event_btnAtrasCadenaActionPerformed

    private void btnAtrasSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasSimboloActionPerformed
        if (controlador != null) {
            controlador.retrocederSimbolo();
        }
    }//GEN-LAST:event_btnAtrasSimboloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelImagen;
    private javax.swing.JButton btnAdelanteSimbolo;
    private javax.swing.JButton btnAtrasCadena;
    private javax.swing.JButton btnAtrasSimbolo;
    private javax.swing.JButton btnSiguienteCadena;
    private javax.swing.JTextField cadenaEvaluada;
    private javax.swing.JTextField elementoEvaluado;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regresarPagina;
    private javax.swing.JTable tablaSentencias;
    // End of variables declaration//GEN-END:variables
}
