package vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import controlador.mostrarDatosControlador;
import controlador.analizarCadenasControlador;
import javax.swing.JPanel;
import controlador.AutomataControlador;
import java.util.Set;
import javax.swing.JLabel;
import modelo.Automata;


/**
 *
 * @author jciri
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
    }

    //------------------------llenar los datos del textarea para las tablas----------------------
    //--obtener la informacion del textarea
    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }
    

    //---poner toda la informacion en las tablas 
    // get y set de estado incial
    public void setEstadoInicial(JTextField estadoInicial) {
        this.estadoInicial = estadoInicial;
    }

    public JTextField getEstadoInicial() {
        return estadoInicial;
    }

    //get y set en la tabla de aceptacion
    public void setTablaAceptacion1(JTable tablaAceptacion1) {
        this.tablaAceptacion1 = tablaAceptacion1;
    }

    public JTable getTablaAceptacion1() {
        return tablaAceptacion1;
    }

    //get y set en la tabla de transicciones 
    public void setTablaTransicciones(JTable tablaTransicciones) {
        this.tablaTransicciones = tablaTransicciones;
    }

    public JTable getTablaTransicciones() {
        return tablaTransicciones;
    }

    //get y set en la tabla de simbolos
    public void setTablasimbolos1(JTable tablasimbolos1) {
        this.tablasimbolos1 = tablasimbolos1;
    }

    public JTable getTablasimbolos1() {
        return tablasimbolos1;
    }
    
    private analizarCadenasControlador controladorCadenas;    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        guardar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        abrir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        estadoInicial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTransicciones = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAceptacion1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablasimbolos1 = new javax.swing.JTable();
        ingresarDatos = new javax.swing.JButton();
        graficar = new javax.swing.JButton();
        ejemplo2 = new javax.swing.JButton();
        ejemplo1 = new javax.swing.JButton();
        ejemplo3 = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Archivo");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Simbolos: 0,1\nEstados: Q0, Q1,Q2,Q3\nEstado Inicial: Q0\nEstados de aceptacion: Q0\nTransiciones: \nQ2, Q1\nQ3, Q0\nQ0, Q3\nQ1, Q2\n\ncadenas a analizar \n1,0,0,1\n0,0,1,0,1");
        jScrollPane1.setViewportView(jTextArea1);

        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado Inicial");

        estadoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoInicialActionPerformed(evt);
            }
        });

        jLabel3.setText("Estado de aceptacion");

        jLabel6.setText("Simbolos");

        tablaTransicciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "0", "1"
            }
        ));
        jScrollPane2.setViewportView(tablaTransicciones);

        tablaAceptacion1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Aceptacion"
            }
        ));
        jScrollPane3.setViewportView(tablaAceptacion1);

        jLabel7.setText("Transicciones");

        tablasimbolos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Simbolos"
            }
        ));
        jScrollPane5.setViewportView(tablasimbolos1);

        ingresarDatos.setText("Ingresar");
        ingresarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarDatosActionPerformed(evt);
            }
        });

        graficar.setText("Graficar");
        graficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graficarActionPerformed(evt);
            }
        });

        ejemplo2.setText("Ejemplo2");
        ejemplo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplo2ActionPerformed(evt);
            }
        });

        ejemplo1.setText("Ejemplo1");
        ejemplo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplo1ActionPerformed(evt);
            }
        });

        ejemplo3.setText("Ejemplo3");
        ejemplo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemplo3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(abrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ingresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ejemplo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ejemplo2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ejemplo3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(236, 236, 236))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ingresarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(graficar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ejemplo1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ejemplo2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ejemplo3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(estadoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
       mostrarDatosControlador eje = new mostrarDatosControlador(this);
       eje.limpiarVista();
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            try {
                // Crear instancia del controlador y usarlo
                controlador.abrirControlador controladorAbrir = new controlador.abrirControlador();
                String contenido = controladorAbrir.abrirArchivo(archivoSeleccionado);
                setTexto(contenido);  // Mostrar en el JTextArea
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Error al leer el archivo: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_abrirActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            try {
                controlador.abrirControlador controlador = new controlador.abrirControlador();
                String contenido = getTexto(); // asegúrate que existe getTexto()
                controlador.guardarArchivo(archivoSeleccionado, contenido);
                JOptionPane.showMessageDialog(this, "Archivo guardado exitosamente.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this,
                        "Error al guardar el archivo: " + ex.getMessage(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de que quieres borrar el contenido actual?",
                "Confirmar nuevo documento",
                JOptionPane.YES_NO_OPTION);

        if (opcion == JOptionPane.YES_OPTION) {
            // Limpiar el JTextArea
            setTexto("");

            // Limpiar el estado inicial
            getEstadoInicial().setText("");

            // Limpiar tabla de aceptación
            javax.swing.table.DefaultTableModel modeloAceptacion
                    = (javax.swing.table.DefaultTableModel) getTablaAceptacion1().getModel();
            modeloAceptacion.setRowCount(0);

            // Limpiar tabla de símbolos
            javax.swing.table.DefaultTableModel modeloSimbolos
                    = (javax.swing.table.DefaultTableModel) getTablasimbolos1().getModel();
            modeloSimbolos.setRowCount(0);

            // Limpiar tabla de transiciones
            javax.swing.table.DefaultTableModel modeloTransiciones
                    = (javax.swing.table.DefaultTableModel) getTablaTransicciones().getModel();
            modeloTransiciones.setRowCount(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void estadoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoInicialActionPerformed

    private void ingresarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarDatosActionPerformed
        mostrarDatosControlador me = new mostrarDatosControlador(this);
        me.ingresarDatos();

    }//GEN-LAST:event_ingresarDatosActionPerformed

    private void graficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graficarActionPerformed
     //cambios        
    grafica vistaGrafica = new grafica();
    analizarCadenasControlador controladorCadenas = new analizarCadenasControlador(this, vistaGrafica);
    vistaGrafica.setControlador(controladorCadenas); // 🔹 conecta la vista con el controlador
    controladorCadenas.ingresarDatos();
    vistaGrafica.setVisible(true);
    
    // Obtener el autómata desde el otro controlador 
    mostrarDatosControlador controladorDatos = new mostrarDatosControlador(this);
    controladorDatos.ingresarDatos();
    Automata automata = controladorDatos.getAutomata();

    if (automata == null) {
        JOptionPane.showMessageDialog(this, "No hay un autómata cargado.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }


    // Crear el controlador de automata
    AutomataControlador controladorAutomata = new AutomataControlador(automata);

    // Definir rutas (puedes cambiarlas)
    String pathDot = "C:/Program Files/Graphviz/bin/dot.exe";
    String rutaEntrada = "C:/AutomataFinito/tmp/entradaGraphviz.txt";
    String rutaSalida = "C:/AutomataFinito/tmp/salidaAutomata.png";

    // Llamar al método que genera la imagen
                // 🔹 Supongamos que el automata tiene un método getEstadoActual()
            Set<String> estadosActivos = new java.util.HashSet<>();
            estadosActivos.add(automata.getEstadoActual());
    controladorAutomata.generarImagenAutomata(pathDot, rutaEntrada, rutaSalida, vistaGrafica.getLabelImagen(), estadosActivos);
    
///hizimos un cambio aca
    controladorCadenas = new analizarCadenasControlador(this, vistaGrafica);
    controladorCadenas.setAutomata(automata);
    controladorCadenas.ingresarDatos();
    vistaGrafica.setControlador(controladorCadenas);
 
    
    }//GEN-LAST:event_graficarActionPerformed

    private void ejemplo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplo2ActionPerformed
       mostrarDatosControlador eje = new mostrarDatosControlador(this);
       eje.abrirArchivoAutomata2();
    }//GEN-LAST:event_ejemplo2ActionPerformed

    private void ejemplo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplo1ActionPerformed
       mostrarDatosControlador eje = new mostrarDatosControlador(this);
       eje.abrirArchivoAutomata1();
       
    }//GEN-LAST:event_ejemplo1ActionPerformed

    private void ejemplo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemplo3ActionPerformed
       mostrarDatosControlador eje = new mostrarDatosControlador(this);
       eje.abrirArchivoAutomata3();
    }//GEN-LAST:event_ejemplo3ActionPerformed

    public void setTexto(String texto) {
        jTextArea1.setText(texto);
    }

    public String getTexto() {
        return jTextArea1.getText();  // o el nombre de tu área de texto
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton ejemplo1;
    private javax.swing.JButton ejemplo2;
    private javax.swing.JButton ejemplo3;
    private javax.swing.JTextField estadoInicial;
    private javax.swing.JButton graficar;
    private javax.swing.JButton guardar;
    private javax.swing.JButton ingresarDatos;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTable tablaAceptacion1;
    private javax.swing.JTable tablaTransicciones;
    private javax.swing.JTable tablasimbolos1;
    // End of variables declaration//GEN-END:variables
}


//QC
//hay que probar si el codigo permite ingresar otros datos en lso archivos y que cree filas extras segun los datos que se ingresan
